# Generated by Django 5.0.4 on 2026-06-13 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFlightInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline_code', models.CharField(help_text="e.g. '6E'", max_length=10)),
                ('airline_name', models.CharField(help_text="e.g. 'IndiGo'", max_length=100)),
                ('flight_number', models.CharField(help_text="e.g. '6E-2012'", max_length=20)),
                ('origin', models.CharField(help_text="3-letter IATA code, e.g. 'DEL'", max_length=3)),
                ('destination', models.CharField(help_text="3-letter IATA code, e.g. 'BOM'", max_length=3)),
                ('departure_datetime', models.DateTimeField(help_text='Departure date and time.')),
                ('arrival_datetime', models.DateTimeField(help_text='Arrival date and time.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price.', max_digits=12)),
                ('seats_available', models.IntegerField(default=10, help_text='Number of available seats.')),
                ('cabin_class', models.CharField(default='Economy', help_text='Economy, Business, etc.', max_length=20)),
                ('duration', models.CharField(default='2h 0m', help_text="Flight duration, e.g. '2h 15m'", max_length=50)),
                ('is_refundable', models.BooleanField(default=True, help_text='Is the ticket refundable?')),
                ('baggage_check_in', models.CharField(default='15 Kg', help_text="e.g. '15 Kg'", max_length=50)),
                ('baggage_hand', models.CharField(default='7 Kg', help_text="e.g. '7' Kg", max_length=50)),
                ('agent', models.ForeignKey(help_text='The agent who owns this pre-purchased flight inventory.', on_delete=django.db.models.deletion.CASCADE, related_name='flight_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Flight Inventory',
                'verbose_name_plural': 'Agent Flight Inventories',
                'ordering': ['-created_at'],
            },
        ),
    ]
