# Generated by Django 5.0.4 on 2026-06-14 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline_code', models.CharField(max_length=10)),
                ('airline_name', models.CharField(blank=True, default='', max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seats_available', models.PositiveIntegerField()),
                ('cabin_class', models.CharField(default='Economy', max_length=20)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('is_refundable', models.BooleanField(default=True)),
                ('baggage_check_in', models.CharField(blank=True, default='', max_length=50)),
                ('baggage_hand', models.CharField(blank=True, default='', max_length=50)),
                ('segments', models.JSONField(blank=True, db_column='segments', default=list, null=True)),
                ('created_by', models.ForeignKey(db_column='agent_id', on_delete=django.db.models.deletion.CASCADE, related_name='flight_inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flight Inventory',
                'verbose_name_plural': 'Flight Inventory',
                'db_table': 'flights_agentflightinventory',
                'ordering': ['-departure_datetime', '-created_at'],
            },
        ),
    ]
