# Generated by Django 5.0.4 on 2026-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentflightinventory',
            name='segments',
            field=models.JSONField(blank=True, help_text='JSON list containing segments details for multi-segment flights.', null=True),
        ),
    ]
