# Generated by Django 5.0.4 on 2026-06-07 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('group_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('FARE_QUOTED', 'Fare Quoted'), ('NEGOTIATION', 'Negotiation'), ('ACCEPTED', 'Accepted'), ('PAYMENT_PENDING', 'Payment Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('PNR_CREATED', 'PNR Created'), ('NAME_SUBMITTED', 'Name Submitted'), ('TICKETED', 'Ticketed'), ('COMPLETED', 'Completed')], default='NEW_REQUEST', max_length=50)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('trip_type', models.CharField(choices=[('ONE_WAY', 'One-Way'), ('ROUND_TRIP', 'Round-Trip'), ('MULTI_CITY', 'Multi-City')], default='ROUND_TRIP', max_length=20)),
                ('cabin_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM', 'Premium Economy'), ('BUSINESS', 'Business')], default='ECONOMY', max_length=20)),
                ('pax_adults', models.IntegerField(default=10)),
                ('pax_children', models.IntegerField(default=0)),
                ('pax_infants', models.IntegerField(default=0)),
                ('expected_fare_per_pax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('airline_preference', models.CharField(blank=True, max_length=100, null=True)),
                ('timing_preference', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=20, null=True)),
                ('group_category', models.CharField(blank=True, max_length=100, null=True)),
                ('pnr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('balance_deadline', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_request_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('change_type', models.CharField(choices=[('UPSIZE', 'Upsize'), ('DOWNSIZE', 'Downsize')], max_length=10)),
                ('pax_delta', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('agent_notes', models.TextField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('adjusted_fare_per_pax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='bookings.groupbooking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.groupbooking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_option_id', models.CharField(max_length=50)),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('fare_per_pax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_per_pax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deposit_per_pax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_deadline', models.DateTimeField()),
                ('balance_deadline', models.DateTimeField()),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='bookings.groupbooking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
