# Generated by Django 5.0.4 on 2026-05-23 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pnr_number', models.CharField(blank=True, help_text='Passenger Name Record (PNR)', max_length=20, null=True)),
                ('ticket_number', models.CharField(blank=True, help_text='Airline Ticket Number', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current issuance status of the ticket.', max_length=20)),
                ('origin', models.CharField(help_text="3-letter IATA departure airport code, e.g. 'DEL'.", max_length=3)),
                ('destination', models.CharField(help_text="3-letter IATA arrival airport code, e.g. 'BOM'.", max_length=3)),
                ('departure_datetime', models.DateTimeField(help_text='Flight departure date and time.')),
                ('arrival_datetime', models.DateTimeField(help_text='Flight arrival date and time.')),
                ('travel_type', models.IntegerField(choices=[(0, 'One-Way'), (1, 'Round-Trip')], default=0, help_text='Trip direction type mapping (0 = One-Way, 1 = Round-Trip).')),
                ('airline_code', models.CharField(help_text="Airline carrier key, e.g. 'AI'.", max_length=10)),
                ('airline_name', models.CharField(blank=True, help_text="Carrier description name, e.g. 'Air India'.", max_length=100, null=True)),
                ('flight_number', models.CharField(help_text="Specific carrier flight tag, e.g. '9757'.", max_length=20)),
                ('cabin_class', models.CharField(blank=True, help_text='Cabin travel tier (Economy, Premium, Business, First).', max_length=20, null=True)),
                ('basic_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Base tariff amount paid.', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax / auxiliary surcharge fees paid.', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Aggregate booking total cost.', max_digits=12)),
                ('currency', models.CharField(default='INR', help_text='Tariff transaction currency code.', max_length=3)),
                ('baggage_check_in', models.CharField(blank=True, help_text='Maximum allowed check-in baggage allowance weight/count.', max_length=50, null=True)),
                ('baggage_hand', models.CharField(blank=True, help_text='Maximum allowed hand baggage allowance weight.', max_length=50, null=True)),
                ('is_refundable', models.BooleanField(default=True, help_text='Identifies if the ticket is eligible for refund on cancellation.')),
                ('food_onboard', models.CharField(blank=True, help_text='Onboard food catering rules/description.', max_length=50, null=True)),
                ('segments_data', models.JSONField(blank=True, default=list, help_text='Chronological segment arrays containing stopover and terminal details.')),
                ('passengers_data', models.JSONField(blank=True, default=list, help_text='Manifest details containing name, document, and gender details of all passengers.')),
                ('user', models.ForeignKey(help_text='The user who bought/owns this ticket.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
