# Generated by Django 5.0.4 on 2026-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booking_ref',
            field=models.CharField(blank=True, help_text="GDS provider Booking_RefNo used for cancellation (e.g. 'FBB64ZDT').", max_length=20, null=True),
        ),
    ]
