# Generated by Django 5.0.4 on 2026-05-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_booking_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flight_id',
            field=models.CharField(blank=True, help_text='GDS flight ID used for cancellation.', max_length=50, null=True),
        ),
    ]
