# Generated by Django 5.0.4 on 2026-06-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ssr_data',
            field=models.JSONField(blank=True, default=dict, help_text='Confirmed passenger-wise Special Service Requests (meals, baggage, seats, etc.)'),
        ),
    ]
