# Generated by Django 5.0.4 on 2026-06-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_ssr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancellation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata regarding ticket cancellation charges, initiator, and refund amounts.'),
        ),
    ]
