# Generated by Django 5.0.4 on 2026-06-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('tickets', '0005_ticket_cancellation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agent_cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason given by agent for cancelling this booking request.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agent_flight_inventory',
            field=models.ForeignKey(blank=True, help_text='Linked agent inventory, if offline booking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='flights.agentflightinventory'),
        ),
    ]
